[tool.poetry]
name = "pyt-intro"
version = "1.0.0"
description = "Einführung in Python"
authors = ["Daniel Senften <daniel.senften@talent-factory.ch>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
jupyter = "^1.1.1"
black = "^25.1.0"
streamlit = "^1.42.0"
notebook = "^7.3.3"
tk = "^0.1.0"
